name: Building Cobbler Packages

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]

jobs:
  build-rockylinux8-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build a Rocky Linux 8 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./tests/build-and-install-rpms.sh rl8 docker/Rocky_Linux_8.dockerfile
  build-fedora33-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build a Fedora 33 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./tests/build-and-install-rpms.sh fc33 docker/Fedora33.dockerfile
  build-debian-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build a Debian 10 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./tests/build-and-install-debs.sh deb10 docker/Debian10.dockerfile
